"""Claude Code session transcripts — the richest telemetry on the machine.

Claude Code appends a JSONL row per event to
``~/.claude/projects/<slugified-cwd>/<session-uuid>.jsonl``. Every ``assistant``
row carries the API response's own ``usage`` block, so the transcripts are a
complete, retroactive record of token consumption: no telemetry to enable, no
Admin key, and history going back to whenever the transcripts were first
written.

**One row is not one API call.** Claude Code writes one ``assistant`` row per
content block of a response, and every one of those rows repeats the *same*
``usage`` object. A resumed or forked session also re-copies earlier rows into
the new session's file. On this machine 2,563 rows collapse to 1,081 real
responses — summing rows would inflate every figure by ~2.4x. Deduplication on
``message.id`` is therefore not an optimization, it is a correctness
requirement, and it is what :func:`collect_usage` exists to do.
"""

from __future__ import annotations

import datetime as dt
import json
import os
from pathlib import Path
from typing import Any, Iterable, Iterator

from . import pricing
from .util import as_int, parse_iso

# Field names shared by the parser, the summarizer and the renderer.
TOKEN_FIELDS = (
    "input_tokens",
    "cache_creation_1h_tokens",
    "cache_creation_5m_tokens",
    "cache_read_input_tokens",
    "output_tokens",
)

GROUPINGS = ("day", "model", "project", "session", "tool", "skill", "effort", "version")

# Short glosses shown beside the data, so the numbers are readable without
# having to know Anthropic's usage vocabulary.
FIELD_NOTES: dict[str, str] = {
    "input_tokens": "fresh prompt tokens, billed at full rate",
    "cache_creation_1h_tokens": "written to the 1-hour prompt cache (2x the input rate)",
    "cache_creation_5m_tokens": "written to the 5-minute prompt cache (1.25x the input rate)",
    "cache_read_input_tokens": "served from cache at ~10% of the input rate",
    "output_tokens": "generated by the model, incl. thinking",
    "total_tokens": "every token the account was charged for",
    "responses": "API responses (deduplicated — not transcript rows)",
    "sessions": "distinct Claude Code sessions seen",
    "web_search_requests": "server-side web searches billed per request",
    "web_fetch_requests": "server-side URL fetches",
    "cost_usd": pricing.ESTIMATE_NOTE,
}

GROUP_NOTES: dict[str, str] = {
    "day": "local calendar day the response was recorded",
    "model": "model that served the request",
    "project": "working directory the session ran in",
    "session": "one `claude` session (resumes keep their id)",
    "tool": "MCP tool credited with the request",
    "skill": "skill active when the request was made",
    "effort": "reasoning effort level requested",
    "version": "Claude Code release that made the request",
}


def projects_dir(config_dir: Path | None = None) -> Path:
    """Where Claude Code keeps transcripts. Honours ``$CLAUDE_CONFIG_DIR``."""
    if config_dir is not None:
        return config_dir / "projects"
    raw = os.environ.get("CLAUDE_CONFIG_DIR", "").strip()
    base = Path(raw).expanduser() if raw else Path.home() / ".claude"
    return base / "projects"


def transcript_files(config_dir: Path | None = None) -> list[Path]:
    """Every transcript, including nested subagent ones.

    Subagents write to ``<project>/<session-uuid>/subagents/<agent>.jsonl``, a
    level deeper than the main session file. Their spend is real — on this
    machine the entire Fable 5 advisor usage lives there — so the search has to
    recurse rather than glob a fixed depth.
    """
    root = projects_dir(config_dir)
    if not root.is_dir():
        return []
    return sorted(root.rglob("*.jsonl"))


def _project_dir(path: Path) -> Path:
    """The ``projects/<slug>`` directory a transcript belongs to."""
    for parent in path.parents:
        if parent.parent.name == "projects":
            return parent
    return path.parent


def project_name(path: Path) -> str:
    """Recover a readable project name from the slugified directory name.

    Claude Code slugifies the cwd by replacing separators with ``-``, so
    ``-Users-abhijitgore-Projects-TokenCheck`` is the best we can do without the
    row's own ``cwd`` field — which :func:`collect_usage` prefers when present.
    """
    slug = _project_dir(path).name
    return slug.lstrip("-").split("-")[-1] or slug


def is_subagent(path: Path) -> bool:
    return "subagents" in path.parts


def iter_rows(path: Path) -> Iterator[dict[str, Any]]:
    """Yield parsed rows, skipping anything unreadable.

    A live session's last line can be a partial write, and older releases wrote
    rows this version doesn't model — neither should abort a report.
    """
    try:
        handle = path.open("r", encoding="utf-8", errors="replace")
    except OSError:
        return
    with handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(row, dict):
                yield row


def _usage_counts(usage: dict[str, Any]) -> dict[str, int]:
    """Flatten one ``usage`` block into the fields TokenCheck reports.

    ``cache_creation`` splits the cache write by TTL, which matters because the
    two are priced differently. Older transcripts only have the flat
    ``cache_creation_input_tokens``; those are attributed to the 5-minute bucket,
    which was the only TTL at the time.
    """
    creation = usage.get("cache_creation")
    creation = creation if isinstance(creation, dict) else {}
    one_hour = as_int(creation.get("ephemeral_1h_input_tokens"))
    five_minute = as_int(creation.get("ephemeral_5m_input_tokens"))
    if not creation:
        five_minute = as_int(usage.get("cache_creation_input_tokens"))

    server_tools = usage.get("server_tool_use")
    server_tools = server_tools if isinstance(server_tools, dict) else {}

    counts = {
        "input_tokens": as_int(usage.get("input_tokens")),
        "cache_creation_1h_tokens": one_hour,
        "cache_creation_5m_tokens": five_minute,
        "cache_read_input_tokens": as_int(usage.get("cache_read_input_tokens")),
        "output_tokens": as_int(usage.get("output_tokens")),
        "web_search_requests": as_int(server_tools.get("web_search_requests")),
        "web_fetch_requests": as_int(server_tools.get("web_fetch_requests")),
    }
    counts["total_tokens"] = sum(counts[field] for field in TOKEN_FIELDS)
    return counts


def _record(row: dict[str, Any], path: Path) -> dict[str, Any] | None:
    """Turn one assistant row into a usage record, or None if it carries none."""
    if row.get("type") != "assistant":
        return None
    message = row.get("message")
    if not isinstance(message, dict):
        return None
    usage = message.get("usage")
    if not isinstance(usage, dict):
        return None

    model = message.get("model")
    if pricing.normalize_model(model) is None:
        # `<synthetic>` rows are Claude Code's own error/notice messages: no
        # API call was made, so there is nothing to count.
        return None

    counts = _usage_counts(usage)
    cwd = row.get("cwd")
    return {
        "id": message.get("id") or row.get("requestId") or row.get("uuid"),
        "request_id": row.get("requestId"),
        "timestamp": row.get("timestamp"),
        "model": model,
        "session": row.get("sessionId") or row.get("session_id"),
        "project": Path(cwd).name if isinstance(cwd, str) and cwd else project_name(path),
        "cwd": cwd,
        "git_branch": row.get("gitBranch"),
        "version": row.get("version"),
        "entrypoint": row.get("entrypoint"),
        "effort": row.get("effort"),
        "speed": usage.get("speed") or message.get("speed"),
        "service_tier": usage.get("service_tier"),
        "is_sidechain": bool(row.get("isSidechain")) or is_subagent(path),
        "is_subagent": is_subagent(path),
        "skill": row.get("attributionSkill"),
        "plugin": row.get("attributionPlugin"),
        "mcp_server": row.get("attributionMcpServer"),
        "tool": row.get("attributionMcpTool"),
        "advisor_model": row.get("advisorModel"),
        "stop_reason": message.get("stop_reason"),
        **counts,
        "cost_usd": pricing.estimate_cost(model, counts),
    }


def collect_usage(
    paths: Iterable[Path] | None = None,
    *,
    since: dt.datetime | None = None,
    project: str | None = None,
    config_dir: Path | None = None,
) -> list[dict[str, Any]]:
    """One record per API response, deduplicated across rows and files.

    Rows sharing a ``message.id`` are the same response written once per content
    block; the largest is kept because a row can be flushed before the response
    finished streaming. ``since`` and ``project`` filter after deduplication so
    a response is never double-counted at a window boundary.
    """
    paths = list(paths) if paths is not None else transcript_files(config_dir)
    seen: dict[str, dict[str, Any]] = {}

    for path in paths:
        for row in iter_rows(path):
            record = _record(row, path)
            if record is None:
                continue
            key = record["id"]
            if key is None:
                # No id to dedupe on: keep it, keyed by identity, rather than
                # silently dropping real usage.
                seen[f"anon:{len(seen)}"] = record
                continue
            previous = seen.get(key)
            if previous is None or record["total_tokens"] > previous["total_tokens"]:
                seen[key] = record

    records = list(seen.values())
    if since is not None:
        records = [r for r in records if _at_or_after(r.get("timestamp"), since)]
    if project:
        needle = project.lower()
        records = [
            r
            for r in records
            if needle in str(r.get("project") or "").lower()
            or needle in str(r.get("cwd") or "").lower()
        ]
    records.sort(key=lambda r: str(r.get("timestamp") or ""))
    return records


def _at_or_after(timestamp: Any, moment: dt.datetime) -> bool:
    parsed = parse_iso(timestamp)
    return parsed is not None and parsed >= moment


def _zero_counts() -> dict[str, Any]:
    counts: dict[str, Any] = {field: 0 for field in TOKEN_FIELDS}
    counts.update(
        total_tokens=0,
        web_search_requests=0,
        web_fetch_requests=0,
        responses=0,
        cost_usd=0.0,
        unpriced_responses=0,
    )
    return counts


def _accumulate(target: dict[str, Any], record: dict[str, Any]) -> None:
    for field in (*TOKEN_FIELDS, "total_tokens", "web_search_requests", "web_fetch_requests"):
        target[field] += record[field]
    target["responses"] += 1
    if record["cost_usd"] is None:
        target["unpriced_responses"] += 1
    else:
        target["cost_usd"] += record["cost_usd"]


def _group_key(record: dict[str, Any], group_by: str) -> str:
    if group_by == "day":
        moment = parse_iso(record.get("timestamp"))
        return moment.astimezone().strftime("%Y-%m-%d") if moment else "unknown"
    if group_by == "session":
        value = record.get("session")
        return str(value)[:8] if value else "unknown"
    value = record.get(group_by)
    if group_by == "tool" and not value:
        value = record.get("mcp_server")
    return str(value) if value else "—"


def summarize(records: list[dict[str, Any]], *, group_by: str | None = None) -> dict[str, Any]:
    """Totals, per-model rows and (optionally) a second grouping."""
    totals = _zero_counts()
    models: dict[str, dict[str, Any]] = {}
    groups: dict[str, dict[str, Any]] = {}
    sessions: set[str] = set()
    projects: set[str] = set()
    sidechain = _zero_counts()

    for record in records:
        _accumulate(totals, record)
        if record.get("session"):
            sessions.add(str(record["session"]))
        if record.get("project"):
            projects.add(str(record["project"]))
        if record.get("is_sidechain"):
            _accumulate(sidechain, record)

        name = str(record.get("model") or "unknown")
        _accumulate(models.setdefault(name, _zero_counts()), record)

        if group_by:
            _accumulate(groups.setdefault(_group_key(record, group_by), _zero_counts()), record)

    totals["sessions"] = len(sessions)
    totals["projects"] = len(projects)

    report: dict[str, Any] = {
        "totals": totals,
        "models": _rows(models, sort_by_name=False),
        "sidechain": sidechain if sidechain["responses"] else None,
        "range": _range(records),
        "source": "local Claude Code transcripts",
        "cost_note": pricing.ESTIMATE_NOTE,
        "field_notes": FIELD_NOTES,
    }
    if group_by:
        report["group_by"] = group_by
        report["group_note"] = GROUP_NOTES.get(group_by, "")
        report["groups"] = _rows(groups, sort_by_name=group_by == "day")
    return report


def _rows(buckets: dict[str, dict[str, Any]], *, sort_by_name: bool) -> list[dict[str, Any]]:
    items = [{"name": name, **values} for name, values in buckets.items()]
    if sort_by_name:
        items.sort(key=lambda item: item["name"])
    else:
        items.sort(key=lambda item: (-item["total_tokens"], item["name"]))
    return items


def _range(records: list[dict[str, Any]]) -> dict[str, Any]:
    stamps = [parse_iso(r.get("timestamp")) for r in records]
    stamps = [s for s in stamps if s is not None]
    if not stamps:
        return {"first": None, "last": None}
    return {"first": min(stamps).isoformat(), "last": max(stamps).isoformat()}
